/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/nfsd_server.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_NFSD_SERVER_H
#define _UAPI_LINUX_NFSD_SERVER_H

#define NFSD_SERVER_FAMILY_NAME		"nfsd_server"
#define NFSD_SERVER_FAMILY_VERSION	1

enum nfsd_rpc_status_comp_attr {
	NFSD_ATTR_RPC_STATUS_COMP_UNSPEC,
	NFSD_ATTR_RPC_STATUS_COMP_OP,

	__NFSD_ATTR_RPC_STATUS_COMP_MAX,
	NFSD_ATTR_RPC_STATUS_COMP_MAX = (__NFSD_ATTR_RPC_STATUS_COMP_MAX - 1)
};

enum nfsd_rpc_status_attr {
	NFSD_ATTR_RPC_STATUS_UNSPEC,
	NFSD_ATTR_RPC_STATUS_XID,
	NFSD_ATTR_RPC_STATUS_FLAGS,
	NFSD_ATTR_RPC_STATUS_PROG,
	NFSD_ATTR_RPC_STATUS_VERSION,
	NFSD_ATTR_RPC_STATUS_PROC,
	NFSD_ATTR_RPC_STATUS_SERVICE_TIME,
	NFSD_ATTR_RPC_STATUS_PAD,
	NFSD_ATTR_RPC_STATUS_SADDR4,
	NFSD_ATTR_RPC_STATUS_DADDR4,
	NFSD_ATTR_RPC_STATUS_SADDR6,
	NFSD_ATTR_RPC_STATUS_DADDR6,
	NFSD_ATTR_RPC_STATUS_SPORT,
	NFSD_ATTR_RPC_STATUS_DPORT,
	NFSD_ATTR_RPC_STATUS_COMPOND_OP,

	__NFSD_ATTR_RPC_STATUS_MAX,
	NFSD_ATTR_RPC_STATUS_MAX = (__NFSD_ATTR_RPC_STATUS_MAX - 1)
};

enum nfsd_commands {
	NFSD_CMD_UNSPEC,
	NFSD_CMD_RPC_STATUS_GET,

	__NFSD_CMD_MAX,
	NFSD_CMD_MAX = (__NFSD_CMD_MAX - 1)
};

enum nfs_opnum4 {
	OP_ACCESS = 3,
	OP_CLOSE = 4,
	OP_COMMIT = 5,
	OP_CREATE = 6,
	OP_DELEGPURGE = 7,
	OP_DELEGRETURN = 8,
	OP_GETATTR = 9,
	OP_GETFH = 10,
	OP_LINK = 11,
	OP_LOCK = 12,
	OP_LOCKT = 13,
	OP_LOCKU = 14,
	OP_LOOKUP = 15,
	OP_LOOKUPP = 16,
	OP_NVERIFY = 17,
	OP_OPEN = 18,
	OP_OPENATTR = 19,
	OP_OPEN_CONFIRM = 20,
	OP_OPEN_DOWNGRADE = 21,
	OP_PUTFH = 22,
	OP_PUTPUBFH = 23,
	OP_PUTROOTFH = 24,
	OP_READ = 25,
	OP_READDIR = 26,
	OP_READLINK = 27,
	OP_REMOVE = 28,
	OP_RENAME = 29,
	OP_RENEW = 30,
	OP_RESTOREFH = 31,
	OP_SAVEFH = 32,
	OP_SECINFO = 33,
	OP_SETATTR = 34,
	OP_SETCLIENTID = 35,
	OP_SETCLIENTID_CONFIRM = 36,
	OP_VERIFY = 37,
	OP_WRITE = 38,
	OP_RELEASE_LOCKOWNER = 39,

	/* nfs41 */
	OP_BACKCHANNEL_CTL = 40,
	OP_BIND_CONN_TO_SESSION = 41,
	OP_EXCHANGE_ID = 42,
	OP_CREATE_SESSION = 43,
	OP_DESTROY_SESSION = 44,
	OP_FREE_STATEID = 45,
	OP_GET_DIR_DELEGATION = 46,
	OP_GETDEVICEINFO = 47,
	OP_GETDEVICELIST = 48,
	OP_LAYOUTCOMMIT = 49,
	OP_LAYOUTGET = 50,
	OP_LAYOUTRETURN = 51,
	OP_SECINFO_NO_NAME = 52,
	OP_SEQUENCE = 53,
	OP_SET_SSV = 54,
	OP_TEST_STATEID = 55,
	OP_WANT_DELEGATION = 56,
	OP_DESTROY_CLIENTID = 57,
	OP_RECLAIM_COMPLETE = 58,

	/* nfs42 */
	OP_ALLOCATE = 59,
	OP_COPY = 60,
	OP_COPY_NOTIFY = 61,
	OP_DEALLOCATE = 62,
	OP_IO_ADVISE = 63,
	OP_LAYOUTERROR = 64,
	OP_LAYOUTSTATS = 65,
	OP_OFFLOAD_CANCEL = 66,
	OP_OFFLOAD_STATUS = 67,
	OP_READ_PLUS = 68,
	OP_SEEK = 69,
	OP_WRITE_SAME = 70,
	OP_CLONE = 71,

	/* xattr support (RFC8726) */
	OP_GETXATTR                = 72,
	OP_SETXATTR                = 73,
	OP_LISTXATTRS              = 74,
	OP_REMOVEXATTR             = 75,

	OP_ILLEGAL = 10044,
};

#endif /* _UAPI_LINUX_NFSD_SERVER_H */
